version: "3.8"

services:
  portal:
    container_name: frontendContainer
    build:
      context: ./ui/frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    container_name: backendContainer
    build:
      context: ./server/GaiaMetrics/
      dockerfile: Dockerfile
    depends_on:
      - sqlServerDb
    ports:
      - "5001:80"
    restart: always
  sqlServerDb:
    container_name: sqlServerContainer
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - dbData:/var/opt/mssql/data
      - ./sqlserver:/var/opt/mssql/restore_file
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStong_Password123#
    # ports:
    #   - "1441:1433"
    restart: always
  mosquitto:
    container_name: mosquittoContainer
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
volumes:
  dbData:
